services:
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6399:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  video-translator:
    image: zxcabs/video-translator:0.0.1-alpha
    container_name: video-translator-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./video:/app/video

volumes:
  redis-data: